version: '3'
services:
  app:
    image: edsoncabrera/22-laboratorio-app:latest
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis01:6379
    depends_on:
      - redis
    command: npm start

  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /home/user/Documents/redis_data:/data